/* autogenerated by Processing revision 1310 on 2026-03-15 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class OCT1 extends PApplet {



final float CAPTURE_DISTANCE = 65;

final float FILL_TIME_MS  = 3000;
final float DRAIN_TIME_MS = 800;

final int   GAMEPLAY_TARGET_CATCHES = 9;
final float CORNER_MARGIN = 70;

final float MAX_SPEED = 3.2f;
final float WANDER_STRENGTH = 0.18f;

final float BG_MARGIN = 90;
final float BG_FOLLOW = 0.65f;

enum Phase { GAMEPLAY, DONE }
Phase phase = Phase.GAMEPLAY;

float progress = 0;


// Firefly
PVector fireflyPos = new PVector();

// grid of fixed spawn positions (3x3)
PVector[] gridPositions;

// Gameplay
int gameplayCatches = 0;
int gridIndex = 0;

// panic movement
PVector fireflyAnchor = new PVector();
PVector fireflyOffset = new PVector();

// BG
PImage bgImage;
String bgFile = "Forest.png";

// Jar cursor
PImage jarOpen;
PImage jarClosed;

// Cap jar size on screen
final float JAR_MAX_W = 150;
final float JAR_MAX_H = 150;

PGraphics glowSprite;
PGraphics scene;
int glowSize = 120;

SoundFile catchSound;
boolean audioStarted = false;
boolean soundDisabled = false;
boolean startSoundPlayed = false;

final int worldW = 800;
final int worldH = 480;

public void setup() {
  /* size commented out by preprocessor */;
  surface.setResizable(false);
  noCursor();

  /* pixelDensity commented out by preprocessor */;
  /* smooth commented out by preprocessor */;

  bgImage = loadImage(bgFile);
  if (bgImage == null) println("ERROR: Could not load background: " + bgFile + " (check /data and filename case)");

  jarOpen = loadImage("jar_open.png");
  if (jarOpen == null) println("ERROR: Could not load jar_open.png (check /data)");

  jarClosed = loadImage("jar_closed.png");
  if (jarClosed == null) println("ERROR: Could not load jar_closed.png (check /data)");

  // Audio
  try {
    catchSound = new SoundFile(this, "Sound.mp3");
    audioStarted = true;
  } catch (Exception e) {
    println("Audio file not found or error loading sound");
    catchSound = null;
    soundDisabled = true;
  }

  glowSprite = createGraphics(glowSize, glowSize);
  glowSprite.smooth(4);
  buildGlowSprite();

  scene = createGraphics(worldW, worldH);
  scene.smooth(4);

  initGridPositions();
  startGameplay();

  playStartSound();
}

public void keyPressed() {
  playStartSound();
}

public void mousePressed() {
  playStartSound();
}

public void draw() {
  float worldMouseX = map(mouseX, 0, width, 0, worldW);
  float worldMouseY = map(mouseY, 0, height, 0, worldH);
  worldMouseX = constrain(worldMouseX, 0, worldW);
  worldMouseY = constrain(worldMouseY, 0, worldH);

  if (phase == Phase.GAMEPLAY) {
    boolean hovering = dist(worldMouseX, worldMouseY, fireflyPos.x, fireflyPos.y) < CAPTURE_DISTANCE;
    updatePanicFirefly(hovering);
  }

  if (phase != Phase.DONE) updateCatchLogic(worldMouseX, worldMouseY);

  renderWorld(scene, worldMouseX, worldMouseY);

  image(scene, 0, 0);
  image(scene, worldW, 0);
}

public void playStartSound() {
  if (startSoundPlayed) return;
  if (!audioStarted || catchSound == null || soundDisabled) return;

  try {
    catchSound.amp(0.3f);
    catchSound.play();
    startSoundPlayed = true;
  } catch (Exception e) {
    startSoundPlayed = false;
  }
}

public void renderWorld(PGraphics g, float mx, float my) {
  g.beginDraw();

  g.background(0);

  if (bgImage != null) {
    float nx = constrain(mx / worldW, 0, 1);
    float ny = constrain(my / worldH, 0, 1);

    float offX = (nx - 0.5f) * 2 * BG_MARGIN * BG_FOLLOW;
    float offY = (ny - 0.5f) * 2 * BG_MARGIN * BG_FOLLOW;

    g.image(bgImage,
      -BG_MARGIN - offX,
      -BG_MARGIN - offY,
      worldW + BG_MARGIN * 2,
      worldH + BG_MARGIN * 2);
  } else {
    g.fill(255);
    g.textAlign(CENTER, CENTER);
    g.text("Missing background image: " + bgFile + "\nPut it in /data and match the exact filename.",
      worldW/2, worldH/2);
  }

  if (phase != Phase.DONE) {
    drawFireflyTo(g, fireflyPos.x, fireflyPos.y);
    drawCatcherTo(g, mx, my, progress);
  } else {
    drawCatcherTo(g, mx, my, 0);
  }

  g.endDraw();
}

public void startGameplay() {
  phase = Phase.GAMEPLAY;
  gameplayCatches = 0;
  gridIndex = 0;
  spawnGridFirefly();
}

public void finishAll() {
  phase = Phase.DONE;
}

public void updateCatchLogic(float x, float y) {
  float d = dist(x, y, fireflyPos.x, fireflyPos.y);
  boolean onTarget = d < CAPTURE_DISTANCE;
  float dt = safeDeltaMs();

  if (onTarget) progress += dt / FILL_TIME_MS;
  else          progress -= dt / DRAIN_TIME_MS;

  progress = constrain(progress, 0, 1);

  if (progress >= 1) {
    playCatchSound();
    progress = 0;

    // gameplay only
    gameplayCatches++;
    gridIndex++;
    if (gameplayCatches >= GAMEPLAY_TARGET_CATCHES) finishAll();
    else spawnGridFirefly();
  }
}

public void spawnGridFirefly() {
  if (gridPositions == null || gridPositions.length == 0) return;
  if (gridIndex < 0) gridIndex = 0;
  if (gridIndex >= gridPositions.length) gridIndex = gridPositions.length - 1;

  fireflyAnchor.set(gridPositions[gridIndex]);
  fireflyOffset.set(0, 0);
  fireflyPos.set(fireflyAnchor);
}

public void updatePanicFirefly(boolean hovering) {
  float dt = safeDeltaMs() / 1000.0f; // seconds

  if (!hovering) {
    float maxOffset = 10;

    float t = millis() * 0.00035f;

    float nx = noise(1000 + t) * 2 - 1;
    float ny = noise(2000 + t) * 2 - 1;

    PVector target = new PVector(nx * maxOffset, ny * maxOffset);

    float ease = 0.10f;
    fireflyOffset.x = lerp(fireflyOffset.x, target.x, ease);
    fireflyOffset.y = lerp(fireflyOffset.y, target.y, ease);

  } else {
    float maxOffset = 34;
    float jitter    = 220;
    float damping   = 0.80f;

    fireflyOffset.x += random(-jitter, jitter) * dt;
    fireflyOffset.y += random(-jitter, jitter) * dt;

    fireflyOffset.mult(damping);

    if (fireflyOffset.mag() > maxOffset) {
      fireflyOffset.normalize().mult(maxOffset);
    }
  }

  fireflyPos.set(fireflyAnchor.x + fireflyOffset.x,
                 fireflyAnchor.y + fireflyOffset.y);

  fireflyPos.x = constrain(fireflyPos.x, 20, worldW - 20);
  fireflyPos.y = constrain(fireflyPos.y, 20, worldH - 20);
}

public void initGridPositions() {
  gridPositions = new PVector[9];
  // positions at corners and centers of edges/center using a margin
  float[] xs = {CORNER_MARGIN, worldW/2.0f, worldW - CORNER_MARGIN};
  float[] ys = {CORNER_MARGIN, worldH/2.0f, worldH - CORNER_MARGIN};
  int k = 0;
  for (int j = 0; j < 3; j++) {
    for (int i = 0; i < 3; i++) {
      gridPositions[k++] = new PVector(xs[i], ys[j]);
    }
  }
}

public float safeDeltaMs() {
  return (frameRate > 0) ? 1000.0f / frameRate : 16;
}

public void buildGlowSprite() {
  glowSprite.beginDraw();
  glowSprite.clear();
  glowSprite.noStroke();
  glowSprite.blendMode(ADD);

  float c = glowSize / 2.0f;
  for (int i = 30; i >= 1; i--) {
    float r = map(i, 1, 30, glowSize * 0.48f, 0);
    float a = map(i, 1, 30, 0, 255) * 0.14f;
    glowSprite.fill(255, 230, 90, a);
    glowSprite.circle(c, c, r * 2);
  }

  glowSprite.blendMode(BLEND);
  glowSprite.fill(255, 255, 210, 240);
  glowSprite.circle(c, c, 10);
  glowSprite.endDraw();
}

public void drawFireflyTo(PGraphics g, float x, float y) {
  float pulse = sin(millis() * 0.003f) * 0.12f + 1.05f;
  g.imageMode(CENTER);
  g.blendMode(ADD);
  g.image(glowSprite, x, y, glowSize * pulse, glowSize * pulse);
  g.blendMode(BLEND);
  g.imageMode(CORNER);
}

// JAR cursor + progress bar
public void drawCatcherTo(PGraphics g, float x, float y, float p) {
  float d = dist(x, y, fireflyPos.x, fireflyPos.y);
  boolean hovering = d < CAPTURE_DISTANCE;

  PImage jar = hovering ? jarClosed : jarOpen;
  if (jar == null) jar = jarOpen;

  if (jar == null) return;

  float s = min(JAR_MAX_W / jar.width, JAR_MAX_H / jar.height);
  s = min(s, 1.0f);

  float drawW = jar.width * s;
  float drawH = jar.height * s;

  g.imageMode(CENTER);
  g.image(jar, x, y, drawW, drawH);

  float frac = constrain(p, 0, 1);
  if (frac > 0) {
    float radius = max(drawW, drawH) * 0.9f;
    float endAngle = -HALF_PI + TWO_PI * frac;

    g.noFill();
    g.blendMode(ADD);

    int glowLayers = 5;
    for (int i = glowLayers; i > 0; i--) {

      float t = i / PApplet.parseFloat(glowLayers);

      float weight = map(t, 0, 1, 2, 10);
      float alpha  = map(t, 0, 1, 20, 100);

      g.stroke(255, 240, 120, alpha);
      g.strokeWeight(weight);

      g.arc(x, y, radius, radius, -HALF_PI, endAngle);
    }

    g.stroke(255, 255, 180);
    g.strokeWeight(4);
    g.arc(x, y, radius, radius, -HALF_PI, endAngle);

    g.blendMode(BLEND);
  }

  g.imageMode(CORNER);
}

public void playCatchSound() {
  if (audioStarted && catchSound != null && !soundDisabled) {
    try {
      catchSound.amp(0.3f);
      catchSound.play();
    } catch (Exception e) {
      soundDisabled = true;
      catchSound = null;
    }
  }
}


  public void settings() { size(1600, 480);
pixelDensity(displayDensity());
smooth(4); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "OCT1" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
